version: "3.3"
services:
  seleniumhub:
    restart: always
    image: selenium/hub:latest
    container_name: seleniumhub
    expose:
      - "4444"
  firefox:
    restart: always
    image: selenium/node-firefox:latest
    container_name: firefox
    depends_on:
      - seleniumhub
    environment:
      - HUB_HOST=seleniumhub
      - HUB_PORT=4444
  chrome:
    restart: always
    image: selenium/node-chrome:latest
    container_name: chrome
    depends_on:
      - seleniumhub
    environment:
      - HUB_HOST=seleniumhub
      - HUB_PORT=4444
  testnode:
    restart: always
    build: 
      context: .
    container_name: testnode
    volumes:
      - ../:/workspace
    depends_on:
      - seleniumhub
      - chrome
      - firefox
    command: sh yarn test